### ISSUE TITLE
BB_glob_amount is nill

### ISSUE THREAD

**Issue by thomaskneisel** [matjojo/BeltBrush#1]
cool to see the code on github :trophy: :+1: 

Looks like the global value isn't set, before the `Place_*`functions use the value.

This check fails `if not game.players[i].gui.top.BB_flow_main then` when you load a game, the GUI isn't reload and the `BB_glob_amount` is not set and remains `nil`.

Maybe you don' need to remeber the `BB_glob_amount` at gui click.

**Comment by thomaskneisel** [comment]
This is just a fix :)

**Comment by matjojo** [comment]
I love that you took the time to rework some of the code, although I do not really understand some of the changes you made, if I understand it right you check the checkboxes every time you place a belt.

I have though about that idea, but I feel like it might use more CPU-time than setting a variable once, I though of fixing this by setting BB_glob_amount at the start of that loop, not in the IF statement that checks if the GUI exists, because that was a bad place for it.

I am not that good with GIT yet, so I have made a new branch called Matjojo-work, in which I'll place the fix I thought of.

again, Thanks a lot for taking all this effort fixing my bugs:)

**Comment by thomaskneisel** [comment]
Your welcome! Yes! Make branch upload your idea and lets talk about it.

yeah well, it might be a bit more CPU-Time but thats no problem.

**Comment by matjojo** [comment]
Hi, I have put some thought in you being willing to help and how I feel about that. First of all I feel like I need to thank you, you probably put a bit of time in the work you did, and I really am grateful for that.

But. I do this for fun, and to learn myself some programming. Sadly I have been put off off this mod jus for the reason that you where helping. It started to feel too much of a MUST do instead of a CAN do. And I really disliked the feeling that that gave. After giving it a lot of though (about two weeks) I came to the conclusion that I will keep the code on Github as I do want to give people a way to look it through easily. But, I am not going to make use of the help of you, or anyone else for that order.

I again want to thank you for being willing to help.


~Matjojo
